apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: mydir
      volumes:
      - name: mydir
        hostPath:
          # Ensure the file directory is created.
          path: /tmp/data
          type: DirectoryOrCreate
      - name: myfile
        hostPath:
          path: /tmp/data/acc.txt
          type: FileOrCreate